version: '3'
services:
  jenkins:
    build: ./jenkins
    ports:
     - "8080:8080"
    environment:
     - "JAVA_OPTS=-Djenkins.install.runSetupWizard=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../github-autostatus-plugin/target/github-autostatus.hpi:/var/jenkins_home/plugins/github-autostatus.hpi
      - ../github-autostatus-plugin/target/github-autostatus.hpi:/var/jenkins_home/plugins/github-autostatus.jpi
    privileged: true
  influx:
    image: "influxdb"
    ports: 
      - "8086:8086"
  grafana:
    image: "grafana/grafana"
    ports: 
      - "3000:3000"